LARGE_FONT = ("Verdana", 12)
MASTER_FONT_COLOUR = "black"
MASTER_BORDER_COLOUR = "black"
UPLOAD_IMG_BTN_COLOUR = "black"
MASTER_COLOUR = "#c9c9c9"
BACKGROUND_COLOUR = "#d7d7d9"
FRAME_BACKGROUND_COLOUR = "#edeef0"
SECONDARY_COLOUR = "#f0f0f0"

PEN_TYPE = 'Line'
LESION_COUNT = 0